version = 3
final_space = true

[[blocks]]
type = 'prompt'
alignment = 'left'

# Display current user and folder
[[blocks.segments]]
type = 'path'
style = 'plain'
background = 'transparent'
foreground = 'blue'
template = '┏[<white> </> <#98bfad>{{ .UserName }}</> on <white> </> <#F5C2E7>{{ .Path }}</>]'

[blocks.segments.properties]
style = 'folder'

# Git status bar
[[blocks.segments]]
type = 'git'
style = 'plain'
foreground = '#6c6c6c'
background = 'transparent'
template = '[ {{ .HEAD }}<cyan>{{ if or (.Working.Changed) (.Staging.Changed) }}*{{end}} {{if gt .Behind 0}}⇣{{end}}{{if gt .Ahead 0}}⇡{{end}}</>]'

[blocks.segments.properties]
fetch_status = true
commit_icon = '@'

[[blocks]]
type = 'rprompt'
overflow = 'hidden'

# Execution Time
[[blocks.segments]]
type = 'executiontime'
style = 'plain'
foreground = 'yellow'
background = 'transparent'
template = '{{ .FormattedMs }} '

[blocks.segments.properties]
threshold = 5000

# Time
[[blocks.segments]]
type = 'time'
style = 'plain'
foreground = '#94ffa2'
template = '{{.CurrentDate | date .Format}}'

[blocks.segments.properties]
time_format = "3:04PM"

# venv
[[blocks.segments]]
type = 'python'
style = 'plain'
foreground = 'green'
template = "  {{ .Venv }}"

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

# Display angle bracket
[[blocks.segments]]
type = 'text'
style = 'plain'
foreground_templates = [
	"{{if gt .Code 0}}red{{end}}",
	"{{if eq .Code 0}}magenta{{end}}",
]
background = 'transparent'
template = '<blue>┗</>❯'

[transient_prompt]
foreground_templates = [
	"{{if gt .Code 0}}red{{end}}",
	"{{if eq .Code 0}}magenta{{end}}",
]
background = 'transparent'
template = '❯'

[secondary.prompt]
foreground = 'magenta'
background = 'transparent'
template = '❯❯'
